### ISSUE TITLE
Portable version? (Suggestion)

### ISSUE THREAD

**Issue by SkylerDaKat** [HKOServer/HKO-re#47]
Portable - an app that can be used on your USB with any computer

I was wondering if it's possible, I'd love to be able to just launch the game anywhere :3

**Comment by Qiangong2** [comment]
Hi Skyler! 

It *should* be possible to run HKO off of a usb. 

You'll need to install it normally the first time so that all the files are extracted successfully.

After:

1) Copy all files in the Hello Kitty Online Program Files folder to your usb
2) Download the latest release of HKO launcher
3) Place HKO launcher in the same folder as autoupdate.exe

Now, when you launch the game using the HKO Launcher, you should be able to run the game portably without admin privileges.

Let us know if it works!

**Comment by SkylerDaKat** [comment]
Oooo alr gimme a minute

**Comment by SkylerDaKat** [comment]
> Hi Skyler!
> 
> It _should_ be possible to run HKO off of a usb.
> 
> You'll need to install it normally the first time so that all the files are extracted successfully.
> 
> After:
> 
>     1. Copy all files in the Hello Kitty Online Program Files folder to your usb
> 
>     2. Download the latest release of HKO launcher
> 
>     3. Place HKO launcher in the same folder as autoupdate.exe
> 
> 
> Now, when you launch the game using the HKO Launcher, you should be able to run the game portably without admin privileges.
> 
> Let us know if it works!

It did work but it did ask me about admin privileges anyways which sucks
What should I do?

**Comment by Redcrafter** [comment]
Oh sorry about that the administrator requirement was baked into the launcher. 
I have updated the launcher to not require admin rights if not necessary.

**Comment by Qiangong2** [comment]
@SkylerDaKat Following the same steps as before, does the updated launcher work?

**Comment by SkylerDaKat** [comment]
> @SkylerDaKat Following the same steps as before, does the updated launcher work?

It loads but I can't verify it works since the computer I used (not the same as the one I installed hko initially) gave me a .net error saying version 6.0 isn't installed, which I don't think it's anything wrong with the software, so idk what to do qwp

**Comment by Redcrafter** [comment]
I have added a standalone version to the latest release that does not require .NET 6 to be installed.

**Comment by SkylerDaKat** [comment]
it loads now, but caviats are, you'd need Clean flash installer pre setup or find a portable version,
My computer straight up did not allow hko to load cuz it got blocked so qwp 
there's nothing I can actually do atm, thanks for the effort tho, this is still useful asf

**Comment by Redcrafter** [comment]
I don't think there's anything we can do about the flash requirement unfortunately. 
I think it is technically possible to install the plugin without administrator rights but that's outside the scope of our project.

**Comment by SkylerDaKat** [comment]
I’ll try putting the installation files on my usb that also has hko, I’ll tell ya if it works

**Comment by SkylerDaKat** [comment]
> I don't think there's anything we can do about the flash requirement unfortunately. I think it is technically possible to install the plugin without administrator rights but that's outside the scope of our project.

IT DOES WORK! Installing the plugin on another pc with admin putting it in the usb lets you play HKO without flaw, I tried it on Windows sandbox :3
