### ISSUE TITLE
trying to log in says "You are already logged in" and then "disconnected from server (2)"

### ISSUE THREAD

**Issue by SkylerDaKat** [HKOServer/HKO-re#48]
it says it whether I put the right password or not, help

**Comment by SkylerDaKat** [comment]
i think I forgot my password
edit: I reset it, I still can't log in

**Comment by Qiangong2** [comment]
@SkylerDaKat Can you please try restarting your machine? For some reason, your machine is spamming the server with login requests

**Comment by SkylerDaKat** [comment]
> @SkylerDaKat Can you please try restarting your machine? For some reason, your machine is spamming the server with login requests
yea that was me, I thought I got the wrong password, so I just started seeing if uppercase or it was lowercase, I plugged my computer to ethernet and I magically managed to log in again

Edit: nvm its doing it again

**Comment by SkylerDaKat** [comment]
I think It's flagging me, I will take this into note whenever I try to login next time, I'm so sorry about the spam, i didn't mean it

**Comment by Redcrafter** [comment]
We don't have any feature of that sort. If you're having issues like that you might have an unstable Internet Connection.
First try closing the game waiting for 30 seconds and opening it again. If that doesn't help try restarting your Computer. 
If you're still having problems after that it's probably an issue on our side.

**Comment by SkylerDaKat** [comment]
> We don't have any feature of that sort. If you're having issues like that you might have an unstable Internet Connection. First try closing the game waiting for 30 seconds and opening it again. If that doesn't help try restarting your Computer. If you're still having problems after that it's probably an issue on our side.

Oh? Well that you mention it, this has been an issue I've had since day one where I get said error but it lets me play on next attempt, yesterday just flat out refused until I waited a bit
